version: "3"
services:
  # graph database using Cayley
  db:
    image: cayleygraph/cayley:v0.7.6
    volumes:
      - "db:/data"
      - "./data:/import"
      - "./etc/cayley.json:/etc/cayley.json"
    ports:
      - 64210:64210

  # shell container to inspect volumes
  shell:
    image: busybox:1.31
    volumes:
      - "db:/data"

volumes:
  db:
