version: '2'

volumes:
  node_modules:
  build_output:

services:
  common:
    build: .
    volumes:
        - ".:/usr/src/app"
        - "node_modules:/usr/src/app/node_modules"
        - "build_output:/usr/src/app/build"

  web:
    extends:
      service: common
    expose:
      - 8080
    ports:
      - "8080:8080"
      - "5858:5858"
    command: npm run docker_web
